github: [catafest]  # Asigură-te că acest utilizator este înscris în GitHub Sponsors
patreon: catafest
liberapay: catafest
issuehunt: bec16af3-6ad4-414a-bbe0-ff265f12a04b
lfx_crowdfunding: catafest
polar: catafest
buy_me_a_coffee: catafest
thanks_dev: catafest
custom:
  - https://sites.google.com/view/festila-george-catalin
  - https://www.linkedin.com/in/c%C4%83t%C4%83lin-george-fe%C8%99til%C4%83-05780a67
  - https://python-catalin.blogspot.com
  - https://graphic-3d.blogspot.com
  - https://catalin-festila.blogspot.com
  - https://pygame-catalin.blogspot.com
